### ISSUE TITLE
readme improvments

### ISSUE THREAD

**Issue by fabianbormann** [Greennav/gn-map#10]
The readme is the classic seed-element readme file. It would be good to replace it by a 
readme contain all attributes and a simple install instruction.

**Comment by jinankjain** [comment]
@fabianbormann I was thinking that a good idea would be to make gh-page ( https://www.polymer-project.org/1.0/docs/start/reusableelements.html#documentation ) for all utilities we have and that easier too.

This will help in improving the doc.

**Comment by jinankjain** [comment]
@fabianbormann  #8 includes the properties and basic usage of gn-map

**Comment by fabianbormann** [comment]
Oh that's right. :+1:
