### ISSUE TITLE
Errors after changing map-type attribute

### ISSUE THREAD

**Issue by fabianbormann** [Greennav/gn-map#9]
Many errors thrown after changing the gn-map "map-type" attribute from default "GoogleMap" to "OpenStreetMap" ..

"Uncaught exception(anonymous function) @ polymer.html:1564Polymer.Base._addFeature._notifyListener @ polymer.html:2016(anonymous function) @ polymer.html:1588Polymer.Base._addFeature.fire @ polymer.html:1335Polymer.Bind._modelApi._notifyChange @ polymer.html:1428Polymer.Base.extend._notifyEffect @ polymer.html:1611Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445setter @ polymer.html:1524(anonymous function) @ polymer.html:3726
polymer.html:1335 Uncaught exceptionPolymer.Base._addFeature.fire @ polymer.html:1335Polymer.Bind._modelApi._notifyChange @ polymer.html:1428Polymer.Base.extend._notifyEffect @ polymer.html:1611Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445setter @ polymer.html:1524(anonymous function) @ polymer.html:3726Polymer.Base.extend._functionEffect @ polymer.html:1615Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445
polymer.html:3726 Uncaught exception(anonymous function) @ polymer.html:3726Polymer.Base.extend._functionEffect @ polymer.html:1615Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445setter @ polymer.html:1524(anonymous function) @ polymer.html:1566Polymer.Base._addFeature._notifyListener @ polymer.html:2016(anonymous function) @ polymer.html:1588Polymer.Base._addFeature.fire @ polymer.html:1335Polymer.Bind._modelApi._notifyChange @ polymer.html:1428Polymer.Base.extend._notifyEffect @ polymer.html:1611
polymer-mini.html:729 Uncaught exceptionDomApi.setAttribute @ polymer-mini.html:729Polymer.Base._addFeature.serializeValueToAttribute @ polymer-micro.html:602Polymer.Base._addFeature.serializeValueToAttribute @ polymer.html:3417Polymer.Base._addFeature.reflectPropertyToAttribute @ polymer-micro.html:593Polymer.Base.extend._reflectEffect @ polymer.html:1607Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445Polymer.Bind._modelApi.__setProperty @ polymer.html:1454Polymer.Base._addFeature._applyEffectValue @ polymer.html:1906Polymer.Base.extend._annotationEffect @ polymer.html:1603"

.. 

![screen](https://cloud.githubusercontent.com/assets/1525818/13550330/8701c6de-e31b-11e5-809a-361f0312bdbf.png)

Don't know if this is a polymer or an internal problem.

**Comment by jinankjain** [comment]
@fabianbormann I got the error. In demo/index.html you forgot to import OpenStreetMap libraries. After importing them everything works fine. I will soon write a patch for this.

**Comment by jinankjain** [comment]
@fabianbormann I don't see any error in my console when I changed from GoogleMap to OpenStreetMap

**Comment by fabianbormann** [comment]
@jinankjain hmm try to change the location after you switched to osm

**Comment by jinankjain** [comment]
@fabianbormann I got your point I googled that error and found that there is some problem with conditional template which leads to such errors https://github.com/Polymer/polymer/issues/656#issuecomment-50306783

**Comment by jinankjain** [comment]
@fabianbormann One more thing I noticed as soon I change from GoogleMap to OpenStreetMap both the map persists on screen, why does GoogleMap does not go away and OpenStreetMap should be shown

**Comment by fabianbormann** [comment]
@jinankjain yeah I know what you mean - it seems that polymer simply
toggles the comment `/* display: none; */` after the element was adding for the fist time 
when the `dom-if` matches.

> `<google-map class="style-scope gn-map" latitude="53.70272116823122" longitude="10.61736007744595" style="/* display: none; */">`

**Comment by jinankjain** [comment]
@fabianbormann yes exactly. And have you seen that link which I had posted from polymer repository. They have this bug with conditional templates

**Comment by fabianbormann** [comment]
@jinankjain yes I saw it but is it the same issue? I was confused because they talk about the `Maximum call stack size exceeded polymer.js:1` problem and we have some listener, notify and effect based problems. I think also think they solved it. Maybe it's better to open a new issue at Polymer/polymer.

**Comment by jinankjain** [comment]
Yes that would be a good option to open  a new issue at polymer.

**Comment by fabianbormann** [comment]
Polymer/polymer#3497

**Comment by maxlorenz** [comment]
Solved using leaflet
